module.exports = {
  API_BASE: 'http://192.168.31.253:8080/api',
  APP_NAME: 'HomeSight 智能户型',
  VERSION: '1.0.0',

  ROOM_COLORS: {
    living:    '#4361ee',
    bedroom:    '#7209b7',
    kitchen:    '#f72585',
    bathroom:   '#06d6a0',
    balcony:    '#ffd166',
    study:      '#fb5607',
    storage:    '#9b5de5',
    other:      '#3a0ca3',
  },

  FURNITURE_ICONS: {
    sofa:       'assets/page-icons/sofa.png',
    bed:        'assets/page-icons/bed.png',
    table:      'assets/page-icons/chair.png',
    wardrobe:   'assets/page-icons/wardrobe.png',
    tv:         'assets/page-icons/tv.png',
    fridge:     'assets/page-icons/fridge.png',
    washer:     'assets/page-icons/washer.png',
    ac:         'assets/page-icons/aircon.png',
    camera:     'assets/page-icons/camera.png',
    speaker:    'assets/page-icons/speaker.png',
    gateway:    'assets/page-icons/sensor.png',
    sensor:     'assets/page-icons/sensor.png',
    desk:       'assets/page-icons/chair.png',
    toilet:     'assets/page-icons/toilet.png',
    shower:     'assets/page-icons/water.png',
    sink:       'assets/page-icons/water.png',
    bathtub:    'assets/page-icons/water.png',
    stove:      'assets/page-icons/stove.png',
    bookshelf:  'assets/page-icons/bookshelf.png',
    curtain:    'assets/page-icons/curtain.png',
  },
};
